name: Run Tests

on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            pip install pytest pytest-cov pandas toml pylint
            pip install . # Install local projects

      - name: Run tests with coverage
        run: |
          pytest life_expectancy/ --cov --cov-report=term-missing

      - name: Run linters
        run: |
          pylint life_expectancy/